name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone https://github.com/container2wasm/container2wasm
          cd container2wasm
          git checkout v0.8.2
          make
          make install
      - run: |
          c2w postgres:17 postgres.wasm
      - uses: actions/upload-artifact@v4
        with:
          path: postgres.wasm
